openapi: 3.0.1
info:
  title: API Notificaciones
  version: "1.0.1"
  description: Endpoints para consultar y marcar notificaciones de los usuarios

servers:
  - url: http://localhost:3000

tags:
  - name: Notificaciones
    description: Operaciones sobre notificaciones de usuarios

paths:

  /notificaciones:
    get:
      tags:
        - Notificaciones
      summary: Obtener todas las notificaciones del usuario autenticado
      description: Retorna todas las notificaciones (leídas y no leídas) del usuario.
      parameters:
        - name: X-User
          in: header
          required: true
          description: Username del usuario
          schema:
            type: string
            example: "jose50"
      responses:
        "200":
          description: Lista de notificaciones del usuario
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Notificacion"
        "401":
          description: Usuario no autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /notificaciones/noleidas:
    get:
      tags:
        - Notificaciones
      summary: Obtener notificaciones no leídas
      description: Retorna solo las notificaciones no leídas del usuario.
      parameters:
        - name: X-User
          in: header
          required: true
          description: Username del usuario autenticado
          schema:
            type: string
            example: "jose50"
      responses:
        "200":
          description: Lista de notificaciones no leídas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Notificacion"
        "401":
          description: Usuario no autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /notificaciones/leidas:
    get:
      tags:
        - Notificaciones
      summary: Obtener notificaciones leídas
      description: Retorna solo las notificaciones leídas del usuario.
      parameters:
        - name: X-User
          in: header
          required: true
          description: Username del usuario
          schema:
            type: string
            example: "jose50"
      responses:
        "200":
          description: Lista de notificaciones leídas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Notificacion"
        "401":
          description: Usuario no autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /notificaciones/{id}:
    patch:
      tags:
        - Notificaciones
      summary: Marcar una notificación como leída
      description: Valida que el ID sea un ObjectId válido, valida permisos, y marca la notificación como leída.
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la notificación
          schema:
            type: string
            example: "654a8f0c3e8f9b0a1d2c3e00"
        - name: X-User
          in: header
          required: true
          description: Username del usuario que marca la notificación
          schema:
            type: string
            example: "jose50"
      responses:
        "200":
          description: Notificación marcada como leída correctamente
          content:
            application/json:
              schema:
                type: string
                example: "La notificacion fue leida"

        "400":
          description: Error de validación (ID inválido)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

        "403":
          description: Usuario sin permiso para marcar esta notificación
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

        "404":
          description: Notificación inexistente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

        "409":
          description: La notificación ya estaba marcada como leída
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  schemas:

    Notificacion:
      type: object
      properties:
        _id:
          type: string
          example: "654a8f0c3e8f9b0a1d2c3e00"
        usuarioDestino:
          type: string
          example: "jose50"
        mensaje:
          type: string
          example: "El pedido 123 cambió a estado ENVIADO"
        leida:
          type: boolean
          example: false
        fechaAlta:
          type: string
          format: date-time
          example: "2025-10-01T12:34:56Z"
        fechaLeida:
          type: string
          format: date-time
          nullable: true
          example: null
        pedido:
          type: number
          example: 123

    Error:
      type: object
      properties:
        name:
          type: string
          example: "ValidationError"
        message:
          type: string
          example: "Los datos ingresados no son correctos"
        details:
          type: array
          nullable: true
          items:
            type: string
