openapi: 3.0.1
info:
  title: API Notificaciones
  version: "1.0.0"
  description: Endpoints para consultar y marcar notificaciones
servers:
  - url: http://localhost:3000

tags:
  - name: Notificaciones
    description: Operaciones sobre notificaciones de usuarios

paths:
  /notificaciones/noleidas:
    get:
      tags:
        - Notificaciones
      summary: Obtener notificaciones no leídas del usuario autenticado
      description: Retorna las notificaciones no leídas del usuario que hace la consulta
      parameters:
        - name: X-User
          in: header
          required: true
          description: Username del usuario
          schema:
            type: string
            example: "jose50"
      responses:
        "200":
          description: Lista de notificaciones no leídas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Notificacion"
              examples:
                ejemplo:
                  value:
                    - _id: "654a8f0c3e8f9b0a1d2c3e00"
                      usuarioDestino: "jose50"
                      mensaje: "El pedido 123 cambió a estado ENVIADO"
                      leida: false
                      fechaAlta: "2025-10-01T12:34:56Z"
        "401":
          description: Usuario no autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /notificaciones/leidas:
    get:
      tags:
        - Notificaciones
      summary: Obtener notificaciones leídas del usuario
      description: Retorna las notificaciones ya leídas del usuario.
      parameters:
        - name: X-User
          in: header
          required: true
          description: Username del usuario
          schema:
            type: string
            example: "jose50"
      responses:
        "200":
          description: Lista de notificaciones leídas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Notificacion"
        "401":
          description: Usuario no autenticado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /notificaciones/{id}:
    patch:
      tags:
        - Notificaciones
      summary: Marcar una notificación como leída
      description: Marca la notificación indicada como leída por el usuario.
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la notificación a marcar como leída
          schema:
            type: string
            example: "654a8f0c3e8f9b0a1d2c3e00"
        - name: X-User
          in: header
          required: true
          description: Username del usuario
          schema:
            type: string
            example: "jose50"
      responses:
        "200":
          description: Notificación marcada como leída correctamente
          content:
            application/json:
              schema:
                type: string
                example: "La notificacion fue leida"
        "403":
          description: Usuario sin permiso para marcar la notificación
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Notificación no encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Notificacion:
      type: object
      properties:
        _id:
          type: string
          example: "654a8f0c3e8f9b0a1d2c3e00"
        usuarioDestino:
          type: string
          example: "jose50"
        mensaje:
          type: string
          example: "El pedido 123 cambió a estado ENVIADO"
        leida:
          type: boolean
          example: false
        fechaAlta:
          type: string
          format: date-time
          example: "2025-10-01T12:34:56Z"
        fechaLeida:
          type: string
          format: date-time
          nullable: true
          example: null

    Error:
      type: object
      properties:
        name:
          type: string
          example: "UsuarioSinPermisoError"
        message:
          type: string
          example: "El usuario no tiene permiso"
        details:
          type: object
          nullable: true
