openapi: 3.0.1
info:
  title: API Pedidos
  version: "1.0.0"
  description: Endpoints para gestionar pedidos (creación, consulta, cambio de estado e historial)
servers:
  - url: http://localhost:3000
tags:
  - name: Pedidos
    description: Operaciones sobre pedidos
paths:
  /pedidos:
    post:
      tags: [Pedidos]
      summary: Crear un pedido
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PedidoDTO'
            examples:
              ejemplo:
                value:
                  comprador: "jose50"
                  vendedor: "vendedor01"
                  moneda: "ARS"
                  items:
                    - productoId: "64a8f0..."
                      cantidad: 2
                    - productoId: "64a8f1..."
                      cantidad: 1
                  direccionEntrega:
                    calle: "Av. Siempre Viva 123"
                    ciudad: "CABA"
                    codigoPostal: "1000"
      responses:
        '201':
          description: Pedido creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pedido'
        '400':
          description: Datos inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Stock insuficiente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /pedidos/{id}:
    get:
      tags: [Pedidos]
      summary: Obtener un pedido por id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "654a8f0c3e8f9b0a1d2c3e00"
      responses:
        '200':
          description: Pedido encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pedido'
        '404':
          description: Pedido no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /pedidos/{id}/cambioDeEstado:
    post:
      tags: [Pedidos]
      summary: Cambiar el estado de un pedido (ej: marcar como ENVIADO)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CambioEstadoDTO'
            examples:
              ejemplo:
                value:
                  usuario:
                    username: "vendedor01"
                    tipoUsuario: "Vendedor"
                  nuevoEstado: "ENVIADO"
                  motivo: "Despachado por logística"
      responses:
        '200':
          description: Estado actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pedido'
        '400':
          description: Cambio inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Usuario no autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /pedidos/historial/{id}:
    get:
      tags: [Pedidos]
      summary: Consultar historial de pedidos de un usuario (comprador)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "64a8f0c3e8f9b0a1d2c3e4f5"
      responses:
        '200':
          description: Lista de pedidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PedidoResumen'
        '404':
          description: No hay historial
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ItemDTO:
      type: object
      required: [productoId, cantidad]
      properties:
        productoId:
          type: string
          example: "64a8f0c3e8f9b0a1d2c3e4f5"
        cantidad:
          type: integer
          example: 2

    Direccion:
      type: object
      required: [calle, ciudad, codigoPostal]
      properties:
        calle:
          type: string
          example: "Av. Siempre Viva 123"
        ciudad:
          type: string
          example: "CABA"
        codigoPostal:
          type: string
          example: "1000"

    PedidoDTO:
      type: object
      required: [comprador, vendedor, items, direccionEntrega]
      properties:
        comprador:
          type: string
          example: "jose50"
        vendedor:
          type: string
          example: "vendedor01"
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemDTO'
        moneda:
          type: string
          example: "ARS"
        direccionEntrega:
          $ref: '#/components/schemas/Direccion'

    CambioEstadoDTO:
      type: object
      required: [usuario, nuevoEstado]
      properties:
        usuario:
          type: object
          properties:
            username:
              type: string
              example: "vendedor01"
            tipoUsuario:
              type: string
              example: "Vendedor"
        nuevoEstado:
          type: string
          enum: [PENDIENTE, CONFIRMADO, ENVIADO, CANCELADO]
          example: "ENVIADO"
        motivo:
          type: string
          example: "Despachado"

    Pedido:
      allOf:
        - $ref: '#/components/schemas/PedidoDTO'
        - type: object
          properties:
            _id:
              type: string
              example: "654a8f0c3e8f9b0a1d2c3e00"
            total:
              type: number
              example: 3500
            estado:
              type: string
              example: "PENDIENTE"
            fechaCreacion:
              type: string
              format: date-time
              example: "2025-10-01T12:34:56Z"

    PedidoResumen:
      type: object
      properties:
        _id:
          type: string
          example: "654a8f0c3e8f9b0a1d2c3e00"
        total:
          type: number
          example: 3500
        moneda:
          type: string
          example: "ARS"
        estado:
          type: string
          example: "ENVIADO"
        fechaCreacion:
          type: string
          format: date-time
          example: "2025-10-01T12:34:56Z"

    Error:
      type: object
      properties:
        message:
          type: string
          example: "Detalle del error"