openapi: 3.0.1
info:
  title: API de Pedidos
  version: "1.0.0"
  description: Endpoints para crear, consultar y actualizar el estado de pedidos.
servers:
  - url: http://localhost:3000
tags:
  - name: Pedidos
    description: Operaciones sobre pedidos

paths:
  /pedidos:
    post:
      tags: [Pedidos]
      summary: Crear un nuevo pedido
      description: El comprador autenticado crea un pedido. El vendedor se asigna automáticamente según los productos.
      security:
        - X-User: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PedidoDTO"
            example:
              itemsDTO:
                - productoID: "64a8f0c3e8f9b0a1d2c3e4f5"
                  cantidad: 2
                - productoID: "64a8f1d2c3e8f9b0a1d2c3e6"
                  cantidad: 1
              moneda: "PESO_ARG"
              direccionEntregaDTO:
                calle: "Av. Siempre Viva"
                altura: 742
                codigoPostal: 1000
                ciudad: "CABA"
                provincia: "Buenos Aires"
                pais: "Argentina"
      responses:
        "201":
          description: Pedido creado correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pedido"
        "400":
          description: Datos inválidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "409":
          description: Stock insuficiente o conflicto de validación
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /pedidos/{id}:
    get:
      tags: [Pedidos]
      summary: Consultar un pedido por ID
      description: Solo pueden verlo el comprador, el vendedor o un administrador.
      security:
        - X-User: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "654a8f0c3e8f9b0a1d2c3e00"
      responses:
        "200":
          description: Pedido encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pedido"
        "403":
          description: Usuario sin permiso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Pedido no encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    patch:
      tags: [Pedidos]
      summary: Cambiar el estado de un pedido
      description: Permite cambiar el estado del pedido (por ejemplo, Confirmado, Enviado, Cancelado). Solo roles autorizados.
      security:
        - X-User: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "654a8f0c3e8f9b0a1d2c3e00"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CambioEstado"
            example:
              estado: "Confirmado"
              motivo: "Pago aprobado"
      responses:
        "200":
          description: Estado actualizado correctamente
          content:
            application/json:
              schema:
                type: string
                example: "El pedido fue confirmado correctamente."
        "400":
          description: Cambio de estado inválido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Usuario no autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Pedido no encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:

  schemas:
    ItemDTO:
      type: object
      required: [productoID, cantidad]
      properties:
        productoID:
          type: string
          example: "64a8f0c3e8f9b0a1d2c3e4f5"
        cantidad:
          type: integer
          example: 2

    DireccionEntregaDTO:
      type: object
      required: [calle, altura, codigoPostal, ciudad, provincia, pais]
      properties:
        calle:
          type: string
          example: "Av. Siempre Viva"
        altura:
          type: integer
          example: 742
        piso:
          type: integer
          example: 2
        departamento:
          type: string
          example: "B"
        codigoPostal:
          type: integer
          example: 1000
        ciudad:
          type: string
          example: "CABA"
        provincia:
          type: string
          example: "Buenos Aires"
        pais:
          type: string
          example: "Argentina"
        latitud:
          type: number
          example: -34.6037
        longitud:
          type: number
          example: -58.3816

    PedidoDTO:
      type: object
      required: [itemsDTO, moneda, direccionEntregaDTO]
      properties:
        itemsDTO:
          type: array
          items:
            $ref: "#/components/schemas/ItemDTO"
        moneda:
          type: string
          enum: [PESO_ARG, DOLAR_USA, REAL]
          example: "PESO_ARG"
        direccionEntregaDTO:
          $ref: "#/components/schemas/DireccionEntregaDTO"

    Pedido:
      allOf:
        - $ref: "#/components/schemas/PedidoDTO"
        - type: object
          properties:
            _id:
              type: string
              example: "654a8f0c3e8f9b0a1d2c3e00"
            comprador:
              type: string
              example: "jose50"
            vendedor:
              type: string
              example: "vendedor01"
            total:
              type: number
              example: 4500
            estado:
              type: string
              example: "Pendiente"
            fechaCreacion:
              type: string
              format: date-time
              example: "2025-10-13T10:00:00Z"

    CambioEstado:
      type: object
      required: [estado]
      properties:
        estado:
          type: string
          enum: [Pendiente, Confirmado, En_Preparacion, Enviado, Entregado, Cancelado]
          example: "Confirmado"
        motivo:
          type: string
          example: "Pago confirmado por el comprador"

    Error:
      type: object
      properties:
        message:
          type: string
          example: "El pedido no existe o el usuario no tiene permiso"
