openapi: 3.0.1
info:
  title: API Productos
  version: "1.0.0"
  description: Documentación de los endpoints de productos
servers:
  - url: http://localhost:3000
tags:
  - name: Productos
    description: Operaciones sobre productos

paths:
  /productos:
    post:
      tags:
        - Productos
      summary: Crear un nuevo producto
      description: Crea un producto asociado al vendedor. El vendedor se obtiene del header `X-User`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductoDTO"
            examples:
              ejemplo:
                value:
                  titulo: "Camisa deportiva"
                  descripcion: "100% algodón, talle M"
                  categoria: "Ropa"
                  precio: 2500
                  moneda: "PESO_ARG"
                  stock: 10
                  fotos:
                    - "https://cdn.ejemplo.com/camisa.jpg"
                  activo: true
      responses:
        "201":
          description: Producto creado correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producto"
        "400":
          description: Datos inválidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: No autorizado (falta header X-User)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    get:
      tags:
        - Productos
      summary: Obtener todos los productos del vendedor
      description: Retorna una lista paginada y filtrada de productos pertenecientes al vendedor.
      parameters:
        - name: X-User
          in: header
          required: true
          description: Username del vendedor
          schema:
            type: string
            example: "jose50"
        - name: pagina
          in: query
          schema:
            type: integer
            example: 1
          description: Número de página
        - name: limite
          in: query
          schema:
            type: integer
            example: 5
          description: Cantidad de productos por página
        - name: minPrecio
          in: query
          schema:
            type: number
            example: 1000
        - name: maxPrecio
          in: query
          schema:
            type: number
            example: 5000
        - name: nombre
          in: query
          schema:
            type: string
            example: "camisa"
        - name: categoria
          in: query
          schema:
            type: string
            example: "Ropa"
        - name: descripcion
          in: query
          schema:
            type: string
            example: "algodón"
        - name: orden
          in: query
          schema:
            type: string
            enum: [precioAsc, precioDesc, masVendido]
            example: "precioAsc"
      responses:
        "200":
          description: Lista paginada de productos del vendedor
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    example: 10
                  pagina:
                    type: integer
                    example: 1
                  limite:
                    type: integer
                    example: 5
                  productos:
                    type: array
                    items:
                      $ref: "#/components/schemas/Producto"
        "401":
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: El vendedor no tiene productos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /productos/{id}:
    patch:
      tags:
        - Productos
      summary: Actualizar un producto existente
      description: Permite al vendedor modificar su propio producto.
      parameters:
        - name: id
          in: path
          required: true
          description: ID del producto a modificar
          schema:
            type: string
            example: "64b1f0c3e8f9b0a1d2c3e4f5"
        - name: X-User
          in: header
          required: true
          description: Username del vendedor
          schema:
            type: string
            example: "jose50"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                precio:
                  type: number
                  example: 2800
                activo:
                  type: boolean
                  example: true
                aumentoStock:
                  type: integer
                  example: 5
      responses:
        "200":
          description: Producto actualizado correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producto"
        "400":
          description: Datos inválidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Usuario no autorizado o sin permiso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Producto no encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    ProductoDTO:
      type: object
      required:
        - titulo
        - descripcion
        - categoria
        - precio
        - moneda
        - stock
        - activo
      properties:
        titulo:
          type: string
          example: "Camisa deportiva"
        descripcion:
          type: string
          example: "100% algodón, talle M"
        categoria:
          type: string
          example: "Ropa"
        precio:
          type: number
          example: 2500
        moneda:
          type: string
          enum: [PESO_ARG, DOLAR_USA, REAL]
          example: "PESO_ARG"
        stock:
          type: integer
          example: 10
        fotos:
          type: array
          items:
            type: string
          example:
            - "https://cdn.ejemplo.com/camisa.jpg"
        activo:
          type: boolean
          example: true

    Producto:
      allOf:
        - $ref: "#/components/schemas/ProductoDTO"
        - type: object
          properties:
            _id:
              type: string
              example: "64b1f0c3e8f9b0a1d2c3e4f5"
            cantVentas:
              type: integer
              example: 12

    Error:
      type: object
      properties:
        name:
          type: string
          example: "ProductoInexistenteError"
        message:
          type: string
          example: "No existe un producto con ese ID"
        details:
          type: object
